### **1. Trasformare cicli in list comprehension**

Fai tre esempi di cicli producono una lista e poi riscrivi lo stesso codice usando la list comprehension

In [6]:
elements= []
for i in range(10):
    elements.append(i)

elements_compressed = [i for i in range(10)]
print(elements)
print(elements_compressed)

#---------------------------------------------------------------------
parola= "parola"
caratteri = []
for letter in parola:
    caratteri.append(letter)
print(caratteri)

caratteri = [letter for letter in parola ]
print(caratteri)

#---------------------------------------------------------------------
elements= []
for i in range(10):
    if i % 2 == 0:
        elements.append(i)

print(elements)
elements_compressed = [i for i in range(10) if i % 2 == 0]
print(elements_compressed)



[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
['p', 'a', 'r', 'o', 'l', 'a']
['p', 'a', 'r', 'o', 'l', 'a']
[0, 2, 4, 6, 8]
[0, 2, 4, 6, 8]


### **2. Vettore di Numeri Primi**

1. **Crea un vettore** contenente tutti i numeri primi compresi tra **0 e 10**  
   _(Puoi scriverli direttamente nell'array)._

2. **Conta quanti numeri ci sono nel vettore** utilizzando la funzione `len()`.  **Ottieni lo stesso numero** accedendo all'attributo `.size` del vettore.

3. Quale pensi sia il tipo di dato (`dtype`) del vettore?  Prova a rispondere senza eseguire il codice e Verifica la tua risposta accedendo all'attributo `.dtype` del vettore

4. Scrivi l'array usando una list comprehension che controlla che i numeri siano primi. 

In [15]:
import numpy as np

vett= np.array([1,2,3,5,7])
print(len(vett))
print(vett.size)
# penso siano interi (codifica 64 bit?)
print(vett.dtype)
def is_prime(n):
    if n == 0:
        return False
    if n== 1:
        return True
    for i in range(2, n):
        if n % i == 0:
            return False
    return True
    
vettore = [x for x in range(10) if is_prime(x)==True ]
print(vettore)


5
5
int64
[1, 2, 3, 5, 7]


### **3.  Operazioni su array**
Crea un array **a**, 1D (senza digitarlo esplicitamente), e genera due nuovi array **b**, contenente una sottostringa a piacere e **c** che è il reverse dell'array **a** (esempio [1,2,3] diventa [3,2,1]) .  Dividi l'array **a** per l'array **c**. Fai la stessa cosa per una lista.

In [36]:
a = np.array([np.random.randint(1, 11) for i in range(10)])
print(a)
b= a.copy()[3:7]
print(b)
c=np.array([a.copy()[-i] for i in range(1, 11)])
print(c)

d=a.copy()/c.copy()
print(d)


print('-----------------------------------------------')
a_base= [np.random.randint(1, 11) for i in range(10)]
print(a_base)
b_base= a_base.copy()[3:7]
print(b_base)
c_base=[a_base.copy()[-i] for i in range(1, 11)]
print(c_base)
#d_base=a_base.copy()/c_base.copy()
#non ha senso dividere una lista per un'altra
print(' ')
print("non ha senso dividere una lista per un'altra")
print(' ')

print(d_base)

[ 7 10  3  6  9  5  2  9  6  4]
[6 9 5 2]
[ 4  6  9  2  5  9  6  3 10  7]
[1.75       1.66666667 0.33333333 3.         1.8        0.55555556
 0.33333333 3.         0.6        0.57142857]
-----------------------------------------------
[9, 6, 10, 9, 9, 6, 5, 7, 8, 7]
[9, 9, 6, 5]
[7, 8, 7, 5, 6, 9, 9, 10, 6, 9]
 
non ha senso dividere una lista per un'altra
 
[0.77777778 2.         1.66666667 0.71428571 0.25       4.
 1.4        0.6        0.5        1.28571429]
