In [7]:
import numpy as np

Using a NumPy function, how would you create a one-dimensional NumPy array of the numbers from 10 to 100, counting by 10?

In [8]:
arr=np.arange(10,110,10) #per generere vettori non va bene lo slicing bisogna usare arrange
print(arr)

[ 10  20  30  40  50  60  70  80  90 100]


How could you create the same NumPy array using a Python range and a list?



In [9]:
arr2=np.array([x for x in range(10,110,10)]) # oppure si può usare la comprensione di lista
print(arr2)

[ 10  20  30  40  50  60  70  80  90 100]


What happens if you pass no arguments to the np.array()?



In [10]:
a=nparray()

NameError: name 'nparray' is not defined

How might you create a NumPy array of the capital letters, A-Z?



In [ ]:
from string import ascii_uppercase
print(np.array(list(ascii_uppercase)))
#oppure
print("\n")
print(np.array([chr(i) for i in range( ord('A'), ord('Z')+1)]))

['A' 'B' 'C' 'D' 'E' 'F' 'G' 'H' 'I' 'J' 'K' 'L' 'M' 'N' 'O' 'P' 'Q' 'R'
 'S' 'T' 'U' 'V' 'W' 'X' 'Y' 'Z']


['A' 'B' 'C' 'D' 'E' 'F' 'G' 'H' 'I' 'J' 'K' 'L' 'M' 'N' 'O' 'P' 'Q' 'R'
 'S' 'T' 'U' 'V' 'W' 'X' 'Y' 'Z']


How would you create a ten-element NumPy array object of all zeros?



In [ ]:
zeros=np.zeros(10)
print(zeros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


How would you find the data type given in #4.

What is the data type for #4?

In [ ]:
#.dtype per vedere che tipo di dato
a=np.array([chr(i) for i in range( ord('A'), ord('Z')+1)])
print(a.dtype)
b=np.zeros(10)
print(b.dtype)

<U1
float64


What function would return the same number of elements, but of all ones?



In [13]:
a= np.ones(7)
print(a)

[1. 1. 1. 1. 1. 1. 1.]


How could you create a ten-element array of random integers between 1 and 5 (inclusive)?



In [29]:
vett=np.random.randint(1,6,10)
print(vett)

[1 3 5 3 4 3 3 4 3 1]


How can you create a normal distribution of 10 numbers, centered on 5?



In [33]:
a=np.random.normal(5,1,10)
print(a)

[4.31410787 5.27347632 5.03062612 4.24859203 3.98988914 4.91271281
 5.63377773 6.66045189 3.89237109 4.44940538]


What code would create an array of 10 random numbers between zero and one?



In [34]:
a=np.random.rand(10)
print(a)

[0.98040908 0.47769487 0.22975995 0.66923525 0.16226129 0.87774512
 0.54217745 0.11516715 0.68513342 0.9322248 ]


Consider the code: np.ones((3,5)). Does this A) create an array of three arrays containing five elements each or B) create an array of five arrays containing three elements each?



In [36]:
a=np.ones((3,5)) #matrice 3x4
print(a)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


Consider an array named “myarray” that is displayed as in the block below. What value does the code myarray[1,2] return? A) 10 B) 7.

Given myarray as shown above, what is the value of myarray.ndim?



In [42]:
myarray=np.array([[ 1,  2,  3,  4],
                  [ 5,  6,  7,  8],
                  [ 9, 10, 11, 12]])
print(myarray)
print(myarray[1][2])  # Stampa la forma della matrice (3, 4)
print("il valore di .nmdim è: ", myarray.ndim)  # Stampa il numero di dimensioni della matrice

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
7
il valore di .nmdim è:  2


An array of three arrays of four elements each like this has twelve elements, of course. How could you create a new array consisting of two arrays of six elements each?

Given new_array from the last exercise, and the code x = new_array, you run the code:



In [112]:
a = np.random.randint(1, 11, size=(2, 6))  # Matrice 2x6 con int casuali 1-104,3
print(a)
b=a.reshape(3,4)
print("\n")
print(b)  # Stampa la matrice 3x4
x=b
print("\n")

print(x)
print("\n")

x[1][2]=100 
print(b)  # Stampa la matrice 3x4
# Modifica il valore in posizione (1, 2) a 100
print("\n")

print(x)  # Stampa la matrice dopo la modifica

print("NB che x e b sono la stessa matrice, quindi modificando x si modifica anche b")

[[ 7  2  9  4  5  4]
 [10  2  8  6  1  9]]


[[ 7  2  9  4]
 [ 5  4 10  2]
 [ 8  6  1  9]]


[[ 7  2  9  4]
 [ 5  4 10  2]
 [ 8  6  1  9]]


[[  7   2   9   4]
 [  5   4 100   2]
 [  8   6   1   9]]


[[  7   2   9   4]
 [  5   4 100   2]
 [  8   6   1   9]]
NB che x e b sono la stessa matrice, quindi modificando x si modifica anche b


How could you create a two-dimensional, 3 x 4 array (three arrays of four elements each) with random numbers from 1 to 10?



In [115]:
a = np.random.randint(1, 11, size=(2, 6))  # Matrice 2x6 con int casuali 1-104,3
print(a)
b=a.reshape(3,4)
c=b.copy()  # Crea una copia di b
print("\n")
print(c)  # Stampa la matrice 3x4
# Modifica il valore in posizione (1, 2) a 100
c[1][2]=100
print("\n")
print(b)  # Stampa la matrice 3x4
print("\n")
print(c)  # Stampa la matrice dopo la modifica
# Modifica il valore in posizione (1, 2) a 100
print("NB che c'è una copia di b, quindi modificando c non si modifica b :)")


[[ 5  5  2  6  1 10]
 [ 9  1  2  4 10  1]]


[[ 5  5  2  6]
 [ 1 10  9  1]
 [ 2  4 10  1]]


[[ 5  5  2  6]
 [ 1 10  9  1]
 [ 2  4 10  1]]


[[  5   5   2   6]
 [  1  10 100   1]
 [  2   4  10   1]]
NB che c'è una copia di b, quindi modificando c non si modifica b :)


How could you create a two-dimensional, 3 x 4 array (three arrays of four elements each) with random numbers from 1 to 10?



How could you create an array of the same size and shape as #17, filled with 64-bit integer zeros?





In [ ]:
values = np.random.randint(1, 11, (3,4))
print(values)
zero=np.zeros(dtype=np.int64, shape=(3,4) )  # Crea una matrice di zeri con la stessa forma di values
print(zero)


[[ 7  9  5 10]
 [ 8  9  4  1]
 [ 8  8  8  9]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


Given this code:

In [120]:
z_list = [z for z in range(0,5)]
y_list = [z_list for y in range(0,4)]
x_list = [y_list for x in range(0,3)]

x_array = np.array(x_list)

What would the value of x_array.shape be?

Given x_array from #19, what is the value for x_array.ndim?

In [132]:
print(x_array.shape)
print(x_array.ndim)  # Stampa il numero di dimensioni della matrice

(3, 4, 5)
3


Given an array, named "arr”, that looks like:

How could you display an array that looks like:



In [ ]:
arr=np.array([[0, 1, 2],
              [3, 4, 5]])

arr1=np.array([[0, 3],
               [1, 4],
               [2, 5]])

In [136]:
arr=np.array([[0, 1, 2],
              [3, 4, 5]])

arr2=arr.T
print(arr2)

[[0 3]
 [1 4]
 [2 5]]


use this array


In [138]:
four_by_five=np.array([[ 1,  2,  3,  4,  5],
                       [ 6,  7,  8,  9, 10],
                       [11, 12, 13, 14, 15],
                       [16, 17, 18, 19, 20]])

Write a statement that prints the first row. 

In [139]:
print(four_by_five[0])

[1 2 3 4 5]


Write an expression to print the last row. (It will be a five-element array).



In [140]:
print(four_by_five[-1])

[16 17 18 19 20]


What does print(four_by_five[2,3]) display?



In [146]:
print(four_by_five[2,3])
print(four_by_five[2][3])


14
14


How could you display the first column? It will be a (four-element array ending with 16.)



In [ ]:
print(four_by_five[:,0])
print("\n")
print(four_by_five[:, 3:])# stampa tutte le righe della colonna 3 in poi
print("\n")
print(four_by_five[1:3, 3:])# stampa le righe 1 e 2 della colonna 3 in poi


[ 1  6 11 16]


[[ 4  5]
 [ 9 10]
 [14 15]
 [19 20]]


[[ 9 10]
 [14 15]]


To keep it simple, let’s use a small one-dimensional array to begin. For exercises #28-36, use the one-dimensional array shown below:

In [164]:
one_dim = np.arange(1,6)
one_dim



array([1, 2, 3, 4, 5])

What would be displayed by

In [ ]:
print(one_dim * 2)
#è sveglio il bro

[ 2  4  6  8 10]


What would be returned by this expression

In [169]:
print(one_dim + np.arange(5, 0, -1))
print(one_dim - one_dim)

[6 6 6 6 6]
[0 0 0 0 0]


In [170]:
one_dim > 2

array([False, False,  True,  True,  True])

For NumPy arrays, logical operations are done with the operators “&” and “|”, rather than the usual Python “and” and “or”. Given that, what would be the result of this expression?

In [171]:
(one_dim > 4) | (one_dim == 1)

array([ True, False, False, False,  True])

In [ ]:
-one_dim

array([-1, -2, -3, -4, -5])

np.absolute take the absolute value of each element. Given that, what would the result be of the following exp

In [175]:
print(np.absolute(-(one_dim[3:])))

[4 5]


This exercise shows the use of one of NumPy’s sequence functions, which operate on the whole array rather than per element. What is returned by one_dim.sum()

In [176]:
one_dim.sum()

np.int64(15)

Break out those pictures of the unit circle for this one, for some trigonometry so simple an ex-history major can do it – well at least I can on a good day.

As background, we can round numbers to a decimal precision using np.around(arr, num_decimals), and get the sine of an angle (in radians) using np.sin. So with that, given the following array of angles in radians:

arr = np.array([0., .5, 1.0, 1.5, 2.0]) * np.pi

What does the following display:

print(np.int32(np.sin(arr)))

In [ ]:
arr = np.array([0., .5, 1.0, 1.5, 2.0]) * np.pi
print(np.sin(arr))  # Calcola il seno degli elementi dell'array

[ 0.0000000e+00  1.0000000e+00  1.2246468e-16 -1.0000000e+00
 -2.4492936e-16]


In [179]:
print(np.int32(np.sin(arr)))


[ 0  1  0 -1  0]
